version: '3.9'

services:
  nginx:
    build: ./nginx
    depends_on:
      - web
    env_file:
      - .env
    ports:
      - 80:80
    restart: "on-failure"
    volumes:
      - static_volume:/code/static
  web:
    build: .
    command: sh -c 'python manage.py makemigrations &&
                    python manage.py migrate --no-input &&
                    python manage.py collectstatic --no-input --clear &&
                    gunicorn main.wsgi:application --bind 0.0.0.0:8000'
    depends_on:
      - db
    env_file:
      - .env
    image: django_app
    ports:
      - 8000:8000
    restart: "on-failure"
    volumes:
      - .:/code
      - static_volume:/code/static
  db:
    env_file:
      - .env
    image: postgres
    restart: "on-failure"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  static_volume:
  postgres_data:
